# Generated by Django 5.1.4 on 2025-01-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=255)),
                ('node_type', models.CharField(default='general', max_length=255)),
                ('task', models.CharField(default='general', max_length=255)),
                ('params', models.JSONField(blank=True, null=True)),
                ('input_dots', models.JSONField(blank=True, null=True)),
                ('output_dots', models.JSONField(blank=True, null=True)),
                ('api_call', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.IntegerField(primary_key=True, serialize=False)),
                ('node_name', models.CharField(max_length=255)),
                ('message', models.CharField(default='Done', max_length=255)),
                ('node_data', models.BinaryField()),
                ('params', models.JSONField(default=dict)),
                ('task', models.CharField(default='general', max_length=255)),
                ('node_type', models.CharField(default='general', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
