# Generated by Django 5.1.4 on 2025-03-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayed_name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('idx', models.IntegerField(default=0)),
                ('category', models.CharField(default='', max_length=255)),
                ('node_name', models.CharField(max_length=255)),
                ('node_type', models.CharField(default='general', max_length=255)),
                ('task', models.CharField(default='general', max_length=255)),
                ('params', models.JSONField(blank=True, null=True)),
                ('input_channels', models.JSONField(blank=True, null=True)),
                ('output_channels', models.JSONField(blank=True, null=True)),
                ('api_call', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('node_name', models.CharField(max_length=255)),
                ('message', models.CharField(default='Done', max_length=255)),
                ('node_data', models.BinaryField(blank=True, null=True)),
                ('params', models.JSONField(default=dict)),
                ('task', models.CharField(default='general', max_length=255)),
                ('node_type', models.CharField(default='general', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
