# Generated by Django 5.2 on 2025-04-28 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('uid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('displayed_name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('idx', models.IntegerField(default=0)),
                ('category', models.CharField(default='', max_length=255)),
                ('node_name', models.CharField(max_length=255)),
                ('node_type', models.CharField(default='general', max_length=255)),
                ('task', models.CharField(default='general', max_length=255)),
                ('params', models.JSONField(blank=True, null=True)),
                ('input_channels', models.JSONField(blank=True, null=True)),
                ('output_channels', models.JSONField(blank=True, null=True)),
                ('api_call', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('node_name', models.CharField(max_length=255)),
                ('message', models.CharField(default='Done', max_length=255)),
                ('node_data', models.CharField(blank=True, max_length=500, null=True)),
                ('params', models.JSONField(default=dict)),
                ('task', models.CharField(default='general', max_length=255)),
                ('node_type', models.CharField(default='general', max_length=255)),
                ('uid', models.BigIntegerField(blank=True, null=True)),
                ('children', models.JSONField(blank=True, default=list, null=True)),
                ('location_x', models.FloatField(default=0.0)),
                ('location_y', models.FloatField(default=0.0)),
                ('input_ports', models.JSONField(default=list)),
                ('output_ports', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='ai_operations.project')),
            ],
        ),
    ]
