# Generated by Django 5.2 on 2025-05-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='displayed_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='node',
            name='parent',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
