# Generated by Django 5.2 on 2025-04-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='uid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='uid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
