# Generated by Django 5.1.2 on 2025-04-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='uid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
