# Generated by Django 5.1.4 on 2025-02-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='displayed_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
