# Generated by Django 5.1.2 on 2025-03-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='children',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
