# Generated by Django 5.2 on 2025-04-29 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='project',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='ai_operations.project'),
        ),
    ]
