# Generated by Django 5.2 on 2025-04-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='id',
        ),
        migrations.AddField(
            model_name='component',
            name='uid',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='node',
            name='uid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
