# Generated by Django 5.1.2 on 2025-03-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_operations', '0002_node_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='children',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
