# Generated by Django 5.1.4 on 2025-02-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_operations', '0002_component_displayed_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='input_dots',
            new_name='input_channels',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='output_dots',
            new_name='output_channels',
        ),
        migrations.AddField(
            model_name='component',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='component',
            name='idx',
            field=models.IntegerField(default=0),
        ),
    ]
