# Generated by Django 5.2 on 2025-04-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_operations', '0002_remove_component_id_component_uid_node_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='uid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
