# Generated by Django 5.2 on 2025-05-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_operations', '0003_alter_node_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='parent',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
