# Generated by Django 5.1.4 on 2025-03-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_operations', '0003_rename_input_dots_component_input_channels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
