# Generated by Django 5.1.2 on 2025-03-22 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_operations', '0003_alter_node_children'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='input_ports',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='node',
            name='location_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='node',
            name='location_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='node',
            name='output_ports',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='node',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='ai_operations.project'),
        ),
    ]
