# Generated by Django 5.1.2 on 2025-03-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_operations', '0004_alter_node_node_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
