# Generated by Django 5.2 on 2025-05-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_operations', '0004_node_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='displayed_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
