# Generated by Django 5.1.2 on 2025-04-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_operations', '0004_project_node_input_ports_node_location_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_data',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
