# Generated by Django 5.1.2 on 2025-03-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_operations', '0005_component_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='idx',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
