# Generated by Django 5.1.4 on 2025-03-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_operations', '0006_alter_component_idx_alter_node_node_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='idx',
            field=models.IntegerField(default=0),
        ),
    ]
