# Generated by Django 5.2 on 2025-06-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_operations', '0006_project_project_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_file',
        ),
    ]
