# Generated by Django 5.2 on 2025-07-04 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_operations', '0009_chatbothistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatBotHistory',
        ),
    ]
